# Generated by Django 2.0.5 on 2019-09-23 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20190627_1613'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': (('menu_slowquery', '菜单 慢查日志'), ('menu_binlog2sql', '菜单 Binlog2SQL'), ('menu_instance', '菜单 实例管理'), ('menu_param', '菜单 参数配置'), ('menu_instance_list', '菜单 实例列表'), ('menu_system', '菜单 系统管理'), ('menu_document', '菜单 相关文档'), ('query_submit', '提交SQL查询'), ('query_all_instances', '可查询所有实例'), ('process_view', '查看会话'), ('process_kill', '终止会话'), ('tablespace_view', '查看表空间'), ('trxandlocks_view', '查看锁信息'), ('param_view', '查看实例参数列表'), ('param_edit', '修改实例参数')),
                'managed': True,
            },
        ),
        migrations.AlterModelOptions(
            name='db_account',
            options={'verbose_name': '账号信息', 'verbose_name_plural': '账号信息'},
        ),
        migrations.AlterModelOptions(
            name='db_instance',
            options={'verbose_name': '实例信息', 'verbose_name_plural': '实例信息'},
        ),
        migrations.AlterModelOptions(
            name='db_name',
            options={'verbose_name': '数据库信息', 'verbose_name_plural': '数据库信息'},
        ),
        migrations.AlterField(
            model_name='db_account',
            name='role',
            field=models.CharField(choices=[('read', 'read_account'), ('write', 'write_account'), ('all', 'all_count'), ('admin', 'admin_count')], default='all', max_length=30),
        ),
        migrations.AlterField(
            model_name='db_account',
            name='tags',
            field=models.CharField(db_index=True, max_length=30, verbose_name='标签'),
        ),
        migrations.AlterField(
            model_name='db_account',
            name='user',
            field=models.CharField(max_length=30, verbose_name='用户名'),
        ),
        migrations.AlterField(
            model_name='db_instance',
            name='charset',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='字符集'),
        ),
        migrations.AlterField(
            model_name='db_instance',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='db_instance',
            name='db_type',
            field=models.CharField(choices=[('mysql', 'MySQL'), ('mongodb', 'MongoDB'), ('mssql', 'MsSQL'), ('redis', 'Redis'), ('pgsql', 'PgSQL'), ('oracle', 'Oracle')], default='mysql', max_length=30, verbose_name='数据库类型'),
        ),
        migrations.AlterField(
            model_name='db_instance',
            name='instance_name',
            field=models.CharField(default='', max_length=50, verbose_name='实例名称'),
        ),
        migrations.AlterField(
            model_name='db_instance',
            name='ip',
            field=models.CharField(max_length=30, verbose_name='IP地址'),
        ),
        migrations.AlterField(
            model_name='db_instance',
            name='port',
            field=models.CharField(max_length=10, verbose_name='端口号'),
        ),
        migrations.AlterField(
            model_name='db_instance',
            name='role',
            field=models.CharField(choices=[('read', 'read'), ('write', 'write'), ('all', 'all'), ('idle', 'idle'), ('admin', 'admin')], max_length=30, verbose_name='角色'),
        ),
        migrations.AlterField(
            model_name='db_instance',
            name='type',
            field=models.CharField(choices=[('main', '主库'), ('subordinate', '从库'), ('alone', '单机')], default='', max_length=6, verbose_name='实例类型'),
        ),
        migrations.AlterField(
            model_name='db_instance',
            name='update_time',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='db_name',
            name='dbname',
            field=models.CharField(max_length=30, verbose_name='数据库名称'),
        ),
        migrations.AlterField(
            model_name='db_name',
            name='dbtag',
            field=models.CharField(max_length=30, unique=True, verbose_name='标签'),
        ),
    ]
