# Generated by Django 2.0.5 on 2019-10-22 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_auto_20191022_1716'),
    ]

    operations = [
        migrations.RenameField(
            model_name='db_instance',
            old_name='ip',
            new_name='host',
        ),
        migrations.AlterUniqueTogether(
            name='db_instance',
            unique_together={('host', 'port')},
        ),
    ]
