# Generated by Django 2.0.5 on 2019-10-29 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_auto_20191022_1735'),
    ]

    operations = [
        migrations.CreateModel(
            name='Query_log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=150, verbose_name='用户名')),
                ('instance_id', models.IntegerField(verbose_name='实例ID')),
                ('dbname', models.CharField(max_length=30, verbose_name='数据库名称')),
                ('sqlcontent', models.TextField(verbose_name='SQL语句')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
        ),
        migrations.AlterField(
            model_name='db_instance',
            name='db_type',
            field=models.CharField(choices=[('MySQL', 'MySQL'), ('MongoDB', 'MongoDB'), ('MsSQL', 'MsSQL'), ('Redis', 'Redis'), ('PgSQL', 'PgSQL'), ('Oracle', 'Oracle')], default='mysql', max_length=30, verbose_name='数据库类型'),
        ),
        migrations.AlterField(
            model_name='db_instance',
            name='role',
            field=models.CharField(choices=[('read', 'read'), ('write', 'write'), ('read_write', 'read_write'), ('idle', 'idle'), ('zabbix', 'zabbix')], max_length=30, verbose_name='角色'),
        ),
        migrations.AlterField(
            model_name='db_instance',
            name='type',
            field=models.CharField(choices=[('主库', '主库'), ('从库', '从库'), ('单机实例', '单机实例')], default='', max_length=6, verbose_name='实例类型'),
        ),
    ]
