# Generated by Django 2.0.5 on 2019-10-29 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_auto_20191029_1643'),
    ]

    operations = [
        migrations.AddField(
            model_name='query_log',
            name='effect_row',
            field=models.IntegerField(default=1, verbose_name='影响的行数'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='query_log',
            name='query_time',
            field=models.CharField(default='', max_length=10, verbose_name='执行耗时'),
        ),
    ]
