#encoding:utf-8
wrong_msg="select '请检查输入语句'"
select_limit=200
export_limit=200
# incp_host="10.xx.xx.xx"
incp_host="127.0.0.1"
public_user="public"
incp_port=6669
incp_user="wzf1"
incp_passwd="root"
sqladvisor_switch = 1
sqladvisor = '/usr/sbin/sqladvisor'
pt_tool = 1
pt_tool_path = '/usr/bin/'
incept_backup_host = '127.0.0.1'
incept_backup_port = '3306'
incept_backup_user = 'wzf1'
incept_backup_passwd = 'root'
path_to_mysqldiff = "/usr/local/bin/mysqldiff"
